sudo: required
dist: trusty
addons:
  apt:
    packages:
#      - mysql-server-5.6
#      - mysql-client-core-5.6
#      - mysql-client-5.6
      - postfix
      - jq
      - nodejs
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
  hosts:
    - travisgento.com
    - travisgento_mysql
services:
  - docker
#  - rabbitmq
#  - elasticsearch
language: php
php:
  - 7.2
node_js:
  - 10.8-
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=1
  matrix:
    - MAGE_VERSION=2.3.1
      - TEST_SUITE=integration
cache:
  apt: true
  directories: $HOME/.composer/cache
before_install:
  - sudo service mysql stop
  # Prepare env variable for current composer module
  - export MODULE_UNDER_TEST_COMPOSER_NAME=`jq -r .name composer.json`
  # Ensure our module is copied rather than symlinked, or templates wont work
  - export COMPOSER_MIRROR_PATH_REPOS=1
  # Copy repo into subdir, so that composer can install it
  - rsync -av . ./module
  # Download Magento
  - wget https://github.com/magento/magento2/archive/${MAGE_VERSION}.zip
  - unzip -qq ${MAGE_VERSION}.zip
  - git clone -b combined https://github.com/Skywire/m2-travis.git
  - cp -R m2-travis/dev magento2-${MAGE_VERSION}/
  - cd magento2-${MAGE_VERSION}/
  # Install module from local filesystem (module subdir)
  - composer config repositories.module_under_test path ../module
  # add packagist repo for any module dependencies
  - composer config --global --auth http-basic.repo.packagist.com tech@skywire.co.uk ${PACKAGIST_KEY}
  - composer config repositories.repo.packagist.com composer https://repo.packagist.com/skywire/
#  # Run before install
#  - chmod +x ./dev/travis/skywire_before_install.sh
#  - ./dev/travis/skywire_before_install.sh
install:
  # Setup Magento and module
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --no-interaction --prefer-dist
  - composer config minimum-stability dev
  - composer require $MODULE_UNDER_TEST_COMPOSER_NAME @dev --prefer-source
  # Install docker
  - git submodule add -b master https://$GITHUB_USER:$GITHUB_TOKEN@github.com/Skywire/skywire-docker.git .docker-install
  - git submodule init
  - cd .docker-install
  - sudo pip install -r requirements.txt
  - python install.py --install-path ../ --domain travisgento.com --mage 2 --php 72 --redis --rabbitmq --elasticsearch --ioncube
  - cd ../
  # Install canned
  - npm install -g canned
  # Run canned against the newly installed module
  - nohup canned vendor/skywire/wordpressapi/src/Test/Integration/canned > /dev/null 2>&1 &
  # Install cypress
  - npm install cypress --save-dev

before_script:
  - chmod +x ./dev/travis/skywire_before_script.sh
  - ./dev/travis/skywire_before_script.sh

  # Start docker
  - docker-compose up -d
  # install Magento
  - mysql -h travisgento_mysql -u root --password=$MYSQL_PASS -e "CREATE DATABASE magento_integration_tests"
  - php bin/magento setup:install --base-url=http://travisgento.com/ --db-host=travisgento_mysql --db-name=magento_integration_tests --db-user=root --db-password=$MYSQL_PASS --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_GB --currency=GBP --timezone=Europe/London --cleanup-database --sales-order-increment-prefix="ORD$" --session-save=db
script:
  # Start cypress tests
  - php bin/magento config:set skywire_wordpress_api/api/base_url http://127.0.0.1:3000
  - php bin/magento config:set skywire_wordpress_api/api/path ""
  - cp ../cypress.json ./cypress.json
  - ./node_modules/.bin/cypress run --record
#after_success:
#  # Run coveralls
#  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
#  - chmod +x php-coveralls.phar
#  - travis_retry php php-coveralls.phar -v