<?php /* @var Skywire\WordpressApi\Block\Post $block */ ?>
<?php $post = $block->getPost() ?>
<article class="row post">
    <?php if ($image = $block->getFeaturedImage()): ?>
        <div class="feature-img" style="background-image:url('<?php echo $image; ?>');"></div>
    <?php endif; ?>

    <div class="entry-header">
        <h2 class="entry-title">
            <a href="<?php echo $block->getPostUrl(); ?>">
                <?php echo $post->getTitle()->getRendered(); ?>
            </a>
        </h2>
    </div>

    <div class="entry-summary">
        <p><?php echo $post->getExcerpt()->getRendered(); ?></p>
        <p><a href="<?php echo $block->getPostUrl(); ?>" class="more-link"><?php echo __('Read more'); ?></a></p>
    </div>
</article>
