name: Magento 2 Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  run_tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-version: ['7.2', '7.3']
    env:
      extensions: bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip, libxml
      key: php-cache-v1 # can be any string, change to clear the extension cache.

    steps:
      - uses: actions/checkout@v2

      - uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: '3.8.2-management-alpine'
          host port: 5672
          rabbitmq user: 'guest'
          rabbitmq password: 'guest'

      - name: Setup PHP cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache PHP extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          coverage: xdebug2
          tools: composer:v1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Configure composer
        run: |
          composer config -g github-protocols https # Only add this if you're testing a public repo. It  will ensure everythings cloned via HTTPS not SSH.
          composer config -g http-basic.repo.magento.com ${{ secrets.MAGENTO_USERNAME}} ${{ secrets.MAGENTO_PASSWORD}}
          composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer config -g http-basic.skywire.repo.repman.io token ${{ secrets.REPMAN_KEY }}
          composer config -g repositories.skywire.repo.repman.io composer https://skywire.repo.repman.io

      - name: Download magento
        id: download-magento
        run: |
          composer create-project --no-install --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.4 ./magento

      - name: Add module under test
        id: add-module
        run: |
          cd magento
          composer require `jq -r .name ../composer.json` dev-${{ github.head_ref }} --prefer-source --no-update
          composer require skywire/m2-actions-workflow ^1.0.0 --prefer-source --no-update
          cd ../

      - name: Install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'magento_integration_tests'
          mysql root password: 123123q

      - name: Install Dependencies
        run: |
          cd magento
          composer install --no-interaction
          cd ../

      - name: Unit Tests
        run: |
          cd magento
          cd dev/tests/unit
          ../../../vendor/bin/phpunit -c phpunit.xml
          cd ../

      - name: Install canned server
        run: sudo npm -g install canned

      - name: Integration Tests
        run: |
          cd magento
          nohup canned vendor/skywire/wordpressapi/src/Test/Integration/canned > /dev/null 2>&1 &
          cd dev/tests/integration
          ../../../vendor/bin/phpunit -c phpunit.xml
          cd ../
